#!/usr/bin/env bash
set -euo pipefail

die() { echo "error: $*" >&2; exit 2; }
have() { command -v "$1" >/dev/null 2>&1; }

usage() {
  cat <<'EOF'
Usage:
  bash tools/install_iflow_watchdog_systemd_user.sh
  bash tools/install_iflow_watchdog_systemd_user.sh --name <instance>
  bash tools/install_iflow_watchdog_systemd_user.sh --workspace <abs_path>
  bash tools/install_iflow_watchdog_systemd_user.sh --name <instance> --workspace <abs_path>

What it does:
  - Installs systemd user instance units:
      ~/.config/systemd/user/iflow-watchdog@.service
      ~/.config/systemd/user/iflow-watchdog@.timer
  - Writes per-instance env file:
      ~/.config/iflow-watchdog/<instance>.env
  - Enables and starts the timer:
      systemctl --user enable --now iflow-watchdog@<instance>.timer

Notes:
  - You can run multiple instances on one server (different --name and --workspace).
  - Unattended mode uses --yolo; only use in test environment.
Defaults:
  - --workspace defaults to current directory (pwd)
  - --name defaults to basename(--workspace)
EOF
}

name=""
workspace=""
while [[ $# -gt 0 ]]; do
  case "$1" in
    --name) name="${2:-}"; shift 2 ;;
    --workspace) workspace="${2:-}"; shift 2 ;;
    -h|--help) usage; exit 0 ;;
    *) die "unknown arg: $1" ;;
  esac
done

if [[ -z "$workspace" ]]; then
  workspace="$(pwd)"
fi

if [[ -z "$name" ]]; then
  name="$(basename "$workspace")"
fi

[[ "$workspace" == /* ]] || die "--workspace must be an absolute path"
[[ -d "$workspace" ]] || die "workspace not found: $workspace"

have systemctl || die "missing: systemctl"

if [[ ! -f "$workspace/AI_WORKSPACE.md" ]] || [[ ! -f "$workspace/REQUIREMENTS.md" ]]; then
  die "workspace must contain AI_WORKSPACE.md and REQUIREMENTS.md: $workspace"
fi

# Best-effort check that systemd --user is available (common pitfall on servers).
if [[ -z "${XDG_RUNTIME_DIR:-}" ]] || ! systemctl --user is-system-running >/dev/null 2>&1; then
  die "systemd --user not running (try: loginctl enable-linger $USER, then re-login)"
fi

unit_dir="$HOME/.config/systemd/user"
env_dir="$HOME/.config/iflow-watchdog"
mkdir -p "$unit_dir" "$env_dir"

src_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
tpl_service="$src_dir/systemd/iflow-watchdog@.service"
tpl_timer="$src_dir/systemd/iflow-watchdog@.timer"
[[ -f "$tpl_service" ]] || die "missing template: $tpl_service"
[[ -f "$tpl_timer" ]] || die "missing template: $tpl_timer"

cp -a "$tpl_service" "$unit_dir/iflow-watchdog@.service"
cp -a "$tpl_timer" "$unit_dir/iflow-watchdog@.timer"

env_file="$env_dir/${name}.env"

# Only allow unattended --yolo if AI_WORKSPACE.md declares test environment.
yo="0"
if grep -Eq '^\s*-\s*environment\s*:\s*"?test"?\s*$' "$workspace/AI_WORKSPACE.md"; then
  yo="1"
fi

cat >"$env_file" <<EOF
# Generated by tools/install_iflow_watchdog_systemd_user.sh
WORKSPACE_DIR=${workspace}
IFLOW_WATCHDOG_ROOT=.
# Unattended mode (uses iflow --yolo). Only safe when environment=test.
IFLOW_WATCHDOG_YOLO=${yo}
# Optional: override logs dir (default: <workspace>/.agentdocs/tmp/server-test)
# IFLOW_WATCHDOG_LOG_DIR=${workspace}/.agentdocs/tmp/server-test
IFLOW_DRAIN_MAX_ENDPOINTS=30
IFLOW_WATCHDOG_SLEEP_S=10
EOF

systemctl --user daemon-reload

if [[ "$yo" == "1" ]]; then
  systemctl --user enable --now "iflow-watchdog@${name}.timer"
  enabled_msg="enabled"
else
  enabled_msg="not enabled (edit IFLOW_WATCHDOG_YOLO=1 after confirming test env)"
fi

echo "OK: installed iflow-watchdog@${name}"
echo "env:  $env_file"
echo "unit: $unit_dir/iflow-watchdog@.service"
echo "timer: iflow-watchdog@${name}.timer ($enabled_msg)"
echo "tune: edit $env_file, then run:"
echo "  systemctl --user daemon-reload"
echo "  systemctl --user restart iflow-watchdog@${name}.service"
if [[ "$yo" != "1" ]]; then
  echo "enable:"
  echo "  systemctl --user enable --now iflow-watchdog@${name}.timer"
fi
